name: docker-hub-registry-ci

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  build-tag-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            adeniyi01/api-node
            adeniyi01/api-golang
            adeniyi01/nginx-frontend
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{date 'YYYYMMDD'}}-{{sha}}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push api-node
        uses: docker/build-push-action@v4
        with:
          file: ./api-node/Dockerfile.9
          context: ./api-node/
          push: true
          # this is to access the tags generated in docker meta
          tags: ${{ steps.meta.outputs.tags }}

      - name: Build and push api-golang
        uses: docker/build-push-action@v4
        with:
          file: ./api-golang/Dockerfile.8
          context: ./api-golang/
          push: true
          # this is to access the tags generated in docker meta
          tags: ${{ steps.meta.outputs.tags }}

      - name: Build and push nginx frontend
        uses: docker/build-push-action@v4
        with:
          file: ./client-react/Dockerfile.5
          context: ./client-react/
          push: true
          # this is to access the tags generated in docker meta
          tags: ${{ steps.meta.outputs.tags }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@latest
        with:
          image-ref: 'adeniyi01/api-node:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'